[bot]
bot = true
token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
token_ftn = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"  
ready_chan = "XXXXXXXXXXXXXXXXXX"

[servers]

    [staf]
        id = "XXXXXXXXXXXXXXXXXX"
        member_count = "XXXXXXXXXXXXXXXXXX"
        welcome_channel = "XXXXXXXXXXXXXXXXXX"
        role_channel = "XXXXXXXXXXXXXXXXXX"     
        bot_role = "XXXXXXXXXXXXXXXXXX"
        description = "XXX"
