[bot]
bot = true
token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
token_ftn = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"  
ready_chan = 0
anonce_vitesse = 0

[servers]

    [staf]
        id = 0
        member_count = 0
        welcome_channel = 0
        role_channel = 0     
        bot_role = 0
        mute_role = 0
        description = "XXX"
