[bot]
bot = true
token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
ready_chan = "XXXXXXXXXXXXXXXXXX"
json_data_base = "XXX"

[servers]

    [staf]
        id = "XXXXXXXXXXXXXXXXXX"
        cat = "XXXXXXXXXXXXXXXXXX"
        channel = "XXXXXXXXXXXXXXXXXX"
